---

- hosts: www
  remote_user: vagrant
  become: yes
  become_user: root
  order: sorted
  tasks:
  - name: Instalacao do nginx
    apt:
      name: nginx
      state: latest
    notify: stop nginx
  handlers:
    - name: stop nginx
      systemd:
        name: httpd
        state: stop
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted




...